/// @description Insert description here
// You can write your code in this editor
layer_sequence_create("Assets_2",(room_width/2),(room_height/2),seq_red_fadeout);
button_highlighted = 0;

splashnum = irandom_range(0,105);
labeltext = "";
if (menu_type == "settings")
{
	settings_get = obj_settings.settings_vol_music;
}


if (splashnum == 0) splashtxt = "Welcome to Gooter!"
else if (splashnum == 1) splashtxt = "Open Source!"
else if (splashnum == 2) splashtxt = "Not Classic!"
else if (splashnum == 3) splashtxt = "Better than Bubsy!"
else if (splashnum == 4) splashtxt = "Made with GameMaker!"
else if (splashnum == 5) splashtxt = "Music made with LMMS!"
else if (splashnum == 6) splashtxt = "Donate on Ko-Fi! (please?)"
else if (splashnum == 7) splashtxt = "The next big game!"
else if (splashnum == 8) splashtxt = "Finally on Linux!"
else if (splashnum == 9) splashtxt = "Pew Pew!"
else if (splashnum == 10) splashtxt = "Pay what you want!"
else if (splashnum == 11) splashtxt = "Contribute on GitHub!"
else if (splashnum == 12) splashtxt = "Not on Roblox!"
else if (splashnum == 13) splashtxt = "Skibidi! (kill me)"
else if (splashnum == 14) splashtxt = "Demo!"
else if (splashnum == 15) splashtxt = "Version 0.1!" // change this with every version
else if (splashnum == 16) splashtxt = "Not like the other top-down shooters! (i've never played one in my life)"
else if (splashnum == 17) splashtxt = "Long-awaited! (by nobody)"
else if (splashnum == 18) splashtxt = "Also play Minecraft!"
else if (splashnum == 19) splashtxt = "Free Palestine!"
else if (splashnum == 20) splashtxt = "Every copy is personalized!"
else if (splashnum == 21) splashtxt = "RUN."
else if (splashnum == 22) splashtxt = "Listen to the soundtrack on Spotify!"
else if (splashnum == 23) splashtxt = "Listen to the soundtrack on Apple Music!"
else if (splashnum == 24) splashtxt = "Listen to the soundtrack on YouTube!"
else if (splashnum == 25) splashtxt = "Listen to the soundtrack on Tidal!"
else if (splashnum == 26) splashtxt = "Listen to the soundtrack on Deezer!"
else if (splashnum == 27) splashtxt = "Listen to the soundtrack on iHeart Radio!"
else if (splashnum == 28) splashtxt = "Listen to the soundtrack on Pandora!"
else if (splashnum == 29) splashtxt = "Listen to the soundtrack on Amazon!"
else if (splashnum == 30) splashtxt = "Buy the soundtrack on Ko-fi!"
else if (splashnum == 31) splashtxt = "Radical!"
else if (splashnum == 32) splashtxt = "Tubular!"
else if (splashnum == 33) splashtxt = "Just a snippet!"
else if (splashnum == 34) splashtxt = "Rebooted and Refreshed!"
else if (splashnum == 35) splashtxt = "Y'all are getting this game!"
else if (splashnum == 36) splashtxt = "Y'all are not getting this game!"
else if (splashnum == 37) splashtxt = "Trans Rights!"
else if (splashnum == 38) splashtxt = "Gay Rights!"
else if (splashnum == 39) splashtxt = "Black Lives Matter!"
else if (splashnum == 40) splashtxt = "Not a scam!"
else if (splashnum == 41) splashtxt = "Scrumptious!"
else if (splashnum == 42) splashtxt = "Banana Woman!"
else if (splashnum == 43) splashtxt = "Sugarplum Woman!"
else if (splashnum == 44) splashtxt = "He's just a little guy!"
else if (splashnum == 45) splashtxt = "Bring back 2012!"
else if (splashnum == 46) splashtxt = "Bring back 2020! :troll:"
else if (splashnum == 47) splashtxt = "!"
else if (splashnum == 48) splashtxt = "Randomized!"
else if (splashnum == 49) splashtxt = "Optimized! (kinda)"
else if (splashnum == 50) splashtxt = "Look into this game's code!"
else if (splashnum == 51) splashtxt = "Shoutouts to Stripes!"
else if (splashnum == 52) splashtxt = "Shoutouts to Moxie!"
else if (splashnum == 53) splashtxt = "Shoutouts to BdenMo!"
else if (splashnum == 54) splashtxt = "Well well well!"
else if (splashnum == 55) splashtxt = "Ugh!"
else if (splashnum == 56) splashtxt = "Yo! Really think so?"
else if (splashnum == 57) splashtxt = "Conceived on January 25th, 2019!"
else if (splashnum == 58) splashtxt = "Giant sunflowers!"
else if (splashnum == 59) splashtxt = "Hidden among a sea of text is this message."
else if (splashnum == 60) splashtxt = "Joe!"
else if (splashnum == 61) splashtxt = "Batman pez dispenser!"
else if (splashnum == 62) splashtxt = "The color palette is epik-216!"
else if (splashnum == 63) splashtxt = "I can't believe it's not Super Mario 64!"
else if (splashnum == 64) splashtxt = "This splash text appears twice!"
else if (splashnum == 65) splashtxt = "This splash text appears twice!"
else if (splashnum == 66) splashtxt = "Better than Overwatch!"
else if (splashnum == 67) splashtxt = "Give me back that Fillet-o-Fish! Give me that fish!"
else if (splashnum == 68) splashtxt = "There's no official Discord server for this game!"
else if (splashnum == 69) splashtxt = "Splash text, huh? Wonder where I've seen that before..."
else if (splashnum == 70) splashtxt = "Way too many splash texts in this game!"
else if (splashnum == 71) splashtxt = "It even comes with a tutorial!"
else if (splashnum == 72) splashtxt = "Moddable!"
else if (splashnum == 73) splashtxt = "Loves his wife!"
else if (splashnum == 74) splashtxt = "There's no secrets in the code!"
else if (splashnum == 75) splashtxt = "Playable on any controller! (but that doesn't mean you should)"
else if (splashnum == 76) splashtxt = "We don't talk about the incident."
else if (splashnum == 77) splashtxt = "Manufactured with love!"
else if (splashnum == 78) splashtxt = "Makes your dreams come alive!"
else if (splashnum == 79) splashtxt = "I'm running out of references!"
else if (splashnum == 80) splashtxt = "Fun for the whole family! (your dog will probably hate it, though)"
else if (splashnum == 81) splashtxt = "Makes Studio Ghibli food look good!"
else if (splashnum == 82) splashtxt = "Just long enough to see my way!"
else if (splashnum == 83) splashtxt = "Find my way! (It's endless)"
else if (splashnum == 84) splashtxt = "Also play This Fish Cannot Swim!"
else if (splashnum == 85) splashtxt = "Better use of your time than Twitter!"
else if (splashnum == 86) splashtxt = "Probably won't sue you!"
else if (splashnum == 87) splashtxt = "If he can shoot, then where's his mouth?"
else if (splashnum == 88) splashtxt = "Triple text!"
else if (splashnum == 89) splashtxt = "Triple text!"
else if (splashnum == 90) splashtxt = "Triple text!"
else if (splashnum == 91) splashtxt = "Listen to the soundtrack on NetEase!"
else if (splashnum == 92) splashtxt = "Listen to the soundtrack on TikTok!"
else if (splashnum == 93) splashtxt = "Listen to the soundtrack on Anghami!"
else if (splashnum == 94) splashtxt = "Listen to the soundtrack on MediaNet!"
else if (splashnum == 95) splashtxt = "Listen to the soundtrack on Boomplay!"
else if (splashnum == 96) splashtxt = "Listen to the soundtrack on Facebook and Instagram!"
else if (splashnum == 97) splashtxt = "Listen to the soundtrack on Adaptr!"
else if (splashnum == 98) splashtxt = "Listen to the soundtrack on Flo!"
else if (splashnum == 99) splashtxt = "Listen to the soundtrack on Claro Musica!"
else if (splashnum == 100) splashtxt = "Listen to the soundtrack on Snapchat!"
else if (splashnum == 101) splashtxt = "Listen to the soundtrack on Joox!"
else if (splashnum == 102) splashtxt = "Listen to the soundtrack on Kuack Media!"
else if (splashnum == 103) splashtxt = "Listen to the soundtrack on Quobuz!"
else if (splashnum == 104) splashtxt = "Listen to the soundtrack on Saavn!"
else if (splashnum == 105) splashtxt = "Listen to the soundtrack on Tencent!"